[build.environment]
  METABOOKS_ENDPOINT="https://www.metabooks.com/api/v2"

  METABOOKS_API_KEYS_METADATA="######"
  METABOOKS_API_KEYS_MMO="######"
  METABOOKS_API_KEYS_COVER="######"

  PUBLISHER_IDS=["SELO1", "SELO2", "SELO3"]

  GATSBY_DEDALOG_COMMERCE_APIKEY="######"